# Generated by Django 6.0.5 on 2026-07-07 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JourneyMap', '0003_travelchecklist_checklistitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiry',
            name='special_request',
        ),
    ]
