# Generated by Django 6.0.5 on 2026-07-08 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JourneyMap', '0004_remove_enquiry_special_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelchecklist',
            name='user',
        ),
        migrations.DeleteModel(
            name='ChecklistItem',
        ),
        migrations.DeleteModel(
            name='TravelChecklist',
        ),
    ]
