# Generated by Django 6.0.5 on 2026-07-08 07:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JourneyMap', '0005_remove_travelchecklist_user_delete_checklistitem_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelBuddy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travel_date', models.DateField()),
                ('budget', models.IntegerField()),
                ('interest', models.CharField(choices=[('Adventure', 'Adventure'), ('Beach', 'Beach'), ('Nature', 'Nature'), ('Hill Station', 'Hill Station'), ('Wildlife', 'Wildlife'), ('Pilgrimage', 'Pilgrimage')], max_length=50)),
                ('about', models.TextField()),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JourneyMap.destination')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
