# Generated by Django 6.0.5 on 2026-07-08 07:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JourneyMap', '0006_travelbuddy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyConverter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('from_currency', models.CharField(choices=[('INR', 'Indian Rupee'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('AED', 'UAE Dirham'), ('JPY', 'Japanese Yen'), ('SGD', 'Singapore Dollar'), ('CAD', 'Canadian Dollar')], max_length=10)),
                ('to_currency', models.CharField(choices=[('INR', 'Indian Rupee'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('AED', 'UAE Dirham'), ('JPY', 'Japanese Yen'), ('SGD', 'Singapore Dollar'), ('CAD', 'Canadian Dollar')], max_length=10)),
                ('converted_amount', models.FloatField(default=0)),
                ('converted_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
