# Generated by Django 6.0.5 on 2026-07-15 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JourneyMap', '0008_emailotp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailOTP',
        ),
    ]
